-- Enums used by OrgSettings (may already exist on fresh deploys)
DO $$ BEGIN
    CREATE TYPE "EmailDesign" AS ENUM ('MODERN_MINIMAL', 'CLASSIC_PROFESSIONAL', 'BRANDED_BOLD');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "InvoiceTemplate" AS ENUM ('CLASSIC', 'MODERN', 'MINIMAL', 'CORPORATE');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "TimeRounding" AS ENUM ('NONE', 'UP_30', 'UP_60', 'DOWN_30', 'DOWN_60');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- Align AutoInvoiceCycle with schema (SEMI_MONTHLY)
ALTER TYPE "AutoInvoiceCycle" ADD VALUE IF NOT EXISTS 'SEMI_MONTHLY';

ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "companyCity" TEXT;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "companyState" TEXT;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "companyCountry" TEXT;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "companyPostalCode" TEXT;

ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "defaultVatIncluded" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "defaultDueDays" INTEGER;

ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "invoiceNumberPrefix" TEXT NOT NULL DEFAULT 'INV';
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "invoiceNumberFormat" TEXT NOT NULL DEFAULT 'YEAR_SEQ';
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "invoiceNumberPadding" INTEGER NOT NULL DEFAULT 4;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "receiptNumberPrefix" TEXT NOT NULL DEFAULT 'REC';
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "receiptNumberFormat" TEXT NOT NULL DEFAULT 'YEAR_SEQ';
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "receiptNumberPadding" INTEGER NOT NULL DEFAULT 4;

ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "emailDesign" "EmailDesign" NOT NULL DEFAULT 'MODERN_MINIMAL';
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "emailAccentColor" TEXT;

ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "defaultInvoiceTemplate" "InvoiceTemplate" NOT NULL DEFAULT 'CLASSIC';
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "showInvoiceStatus" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "invoiceAccentColor" TEXT;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "invoiceFooterText" TEXT;

ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "bankName" TEXT;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "bankIban" TEXT;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "bankBic" TEXT;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "bankAccountHolder" TEXT;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "bankInstructions" TEXT;

ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "privacyGdpr" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "privacyCcpa" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "timeRounding" "TimeRounding" NOT NULL DEFAULT 'NONE';

ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "defaultAutoInvoiceCycle" "AutoInvoiceCycle" NOT NULL DEFAULT 'MONTHLY';
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "semiMonthlyPeriodSplitDay" INTEGER NOT NULL DEFAULT 15;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "semiMonthlyEmitDay1" INTEGER NOT NULL DEFAULT 16;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "semiMonthlyEmitDay2" INTEGER NOT NULL DEFAULT 1;
