mutation FulfillmentCreateWithTracking(
  $fulfillmentOrderId: ID!
  $tracking: FulfillmentTrackingInput!
  $notifyCustomer: Boolean
) {
  fulfillmentCreate(
    fulfillment: {
      lineItemsByFulfillmentOrder: [{ fulfillmentOrderId: $fulfillmentOrderId }]
      trackingInfo: $tracking
      notifyCustomer: $notifyCustomer
    }
  ) {
    fulfillment {
      id
      status
      trackingInfo(first: 5) {
        number
        company
        url
      }
    }
    userErrors {
      field
      message
    }
  }
}
