query GetProductById($id: ID!) {
  shop {
    currencyCode
  }
  product(id: $id) {
    id
    legacyResourceId
    title
    description
    descriptionHtml
    vendor
    productType
    tags
    handle
    status
    publishedAt
    createdAt
    updatedAt
    media(first: 20) {
      edges {
        node {
          __typename
          ... on MediaImage {
            image {
              url
            }
          }
          ... on Video {
            id
          }
          ... on ExternalVideo {
            id
          }
          ... on Model3d {
            id
          }
        }
      }
    }
    variants(first: 100) {
      edges {
        node {
          id
          legacyResourceId
          title
          sku
          barcode
          price
          updatedAt
          selectedOptions {
            name
            value
          }
          media(first: 1) {
            edges {
              node {
                __typename
                ... on MediaImage {
                  image {
                    url
                  }
                }
                ... on Video {
                  id
                }
                ... on ExternalVideo {
                  id
                }
                ... on Model3d {
                  id
                }
              }
            }
          }
        }
      }
    }
  }
}
