[versions]
kotlinVersion = "2.1.20"
ktorVersion = "3.2.0"
kotlinGraphqlVersion = "8.8.1"

[libraries]
graphqlKotlinKtorClient = { group = "com.expediagroup", name = "graphql-kotlin-ktor-client", version.ref = "kotlinGraphqlVersion" }
ktorClientOkhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktorVersion" }
ktorClientLogging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktorVersion" }

[plugins]
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinVersion" }
kotlinGraphql = { id = "com.expediagroup.graphql", version.ref = "kotlinGraphqlVersion" }
