[versions]
kotlinVersion = "2.2.20"
ktorVersion = "3.4.1"
kotlinGraphqlVersion = "9.0.0"
konsistVersion = "0.17.3"

[libraries]
konsist = { group = "com.lemonappdev", name = "konsist", version.ref = "konsistVersion" }
graphqlKotlinKtorClient = { group = "com.expediagroup", name = "graphql-kotlin-ktor-client", version.ref = "kotlinGraphqlVersion" }
graphqlKotlinClientSerialization = { group = "com.expediagroup", name = "graphql-kotlin-client-serialization", version.ref = "kotlinGraphqlVersion" }
ktorClientOkhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktorVersion" }
ktorClientContentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktorVersion" }
ktorSerializationKotlinxJson = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktorVersion" }
ktorServerCio = { group = "io.ktor", name = "ktor-server-cio", version.ref = "ktorVersion" }
ktorServerStatusPages = { group = "io.ktor", name = "ktor-server-status-pages", version.ref = "ktorVersion" }
ktorServerContentNegotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktorVersion" }
ktorServerCallLogging = { group = "io.ktor", name = "ktor-server-call-logging", version.ref = "ktorVersion" }

[plugins]
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinVersion" }
kotlinGraphql = { id = "com.expediagroup.graphql", version.ref = "kotlinGraphqlVersion" }
