package dropnext.dss

import com.lemonappdev.konsist.api.Konsist
import com.lemonappdev.konsist.api.architecture.KoArchitectureCreator.assertArchitecture
import com.lemonappdev.konsist.api.architecture.Layer
import com.lemonappdev.konsist.api.verify.assertFalse
import org.junit.jupiter.api.Test


/** Tests that enforce architecture rules relating to the dependencies that packages have on each other. */
class ArchitectureTest {

  @Test
  fun `the project's packages have correct dependencies on each other`() {
    // Our sources live in `src/` (not `src/main/kotlin/`), which defeats Konsist's
    // built-in production/test detection. Point Konsist at the directory explicitly instead.
    Konsist.scopeFromDirectory("src").assertArchitecture {
      // Define our "layers"
      val config = Layer("config", "dropnext.dss.config..")
      val shopify = Layer("shopify", "dropnext.dss.shopify..")
      val handler = Layer("handler", "dropnext.dss.handler..")
      val routing = Layer("routing", "dropnext.dss.routing..")
      val workflow = Layer("workflow", "dropnext.dss.workflow..")
      val libFulfillment = Layer("lib/fulfillment", "dropnext.dss.lib.fulfillment..")
      val libMonolith = Layer("lib/monolith", "dropnext.dss.lib.monolith..")

      // Define architecture assertions.
      // Note: `lib/dss` is intentionally not a layer here — its `dto` subpackage holds the
      // generated OpenAPI DTOs that virtually every layer depends on, so layer rules against
      // `dropnext.dss.lib.dss..` would always fail.
      config.doesNotDependOn(handler, routing, workflow, libFulfillment, libMonolith)
      // (allowed: config can depend on shopify for `normalizeShopDomain` — a shared helper)
      libMonolith.doesNotDependOn(handler, routing, workflow, libFulfillment, shopify)
      libFulfillment.doesNotDependOn(handler, routing, workflow)
      shopify.doesNotDependOn(handler, routing, workflow, libMonolith)
      workflow.doesNotDependOn(handler, routing) // workflows must not depend on HTTP layer
      routing.doesNotDependOn(workflow)          // routing wires handlers, not workflows directly
    }
  }

  /** Reflection-related imports that are forbidden in production code. */
  private val reflectionImports = listOf(
    "java.lang.reflect.",
    "kotlin.reflect.",
    "java.lang.Class",
  )

  /**
   * Files that are allowed to use reflection because they integrate with libraries that require it
   * (none currently — keep this list empty unless an unavoidable case appears).
   */
  private val reflectionAllowList = listOf<String>()

  @Test
  fun `forbid use of JVM reflection`() {
    Konsist.scopeFromDirectory("src")
      .files
      .filterNot { file -> reflectionAllowList.any { allowed -> allowed in file.path } }
      .assertFalse { file ->
        val forbiddenImports = file.imports
          .map { it.name }
          .filter { importName -> reflectionImports.any { importName.startsWith(it) } }
        if (forbiddenImports.isNotEmpty()) {
          println(
            "ERROR: File ${file.path} uses reflection imports: $forbiddenImports. " +
              "Avoid JVM reflection. If unavoidable, add the file to reflectionAllowList in ArchitectureTest."
          )
        }
        forbiddenImports.isNotEmpty()
      }
  }

  @Test
  fun `main sources do not use wildcard imports`() {
    // Konsist's KoImport.name strips the trailing `.*`, so a Konsist-based check silently passes.
    // We grep the source files directly — no extra dependency, no false negatives.
    val wildcardImportLine = Regex("""^\s*import\s+[\w.]+\.\*\s*$""")
    val violations = java.io.File("src").walkTopDown()
      .filter { it.isFile && it.extension == "kt" }
      .flatMap { file ->
        file.readLines()
          .withIndex()
          .filter { (_, line) -> wildcardImportLine.matches(line) }
          .map { (idx, line) -> "${file.path}:${idx + 1}  ${line.trim()}" }
      }
      .toList()
    assert(violations.isEmpty()) {
      "Wildcard imports are forbidden in production sources — use explicit imports:\n" +
        violations.joinToString("\n")
    }
  }

  @Test
  fun `no hand-written Kotlin under lib_dss_dto`() {
    // DTOs in dropnext.dss.lib.dss.dto are generated by openApiGenerate from openapi.json.
    // Hand-written copies would drift from the spec — find them by looking for any .kt file
    // under src/dropnext/dss/lib/dss/dto/ (sources tree only; generated DTOs live under build/).
    val handWritten = Konsist.scopeFromDirectory("src")
      .files
      .filter { "/dropnext/dss/lib/dss/dto/" in it.path }
    assert(handWritten.isEmpty()) {
      "Hand-written DTOs belong in openapi.json codegen only: ${handWritten.map { it.path }}"
    }
  }
}
